services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - discovery-server

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./data:/app/data
    depends_on:
      discovery-server:
        condition: service_started

  user-service:
    build: ./user-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./data:/app/data
    depends_on:
      discovery-server:
        condition: service_started

  geographic-service:
    build: ./geographic-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./data:/app/data
    depends_on:
      discovery-server:
        condition: service_started

  incident-service:
    build: ./incident-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./data:/app/data
    depends_on:
      discovery-server:
        condition: service_started

  analytics-service:
    build: ./analytics-service
    ports:
      - "8086:8086"
    environment:
      - DATABASE_URL=sqlite:///./data/nisircop.db
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
      - EUREKA_APP_NAME=ANALYTICS-SERVICE
    volumes:
      - ./data:/app/data
    depends_on:
      discovery-server:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway