server:
  port: 8083

spring:
  application:
    name: incident-service
  profiles:
    active: dev # Default to dev profile for local runs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.sqlite.SpatiaLiteDialect
        format_sql: true

# Default Eureka configuration for local development
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlite:data/nisircop.db # Relative path for both local and Docker
    driver-class-name: org.sqlite.JDBC

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:sqlite:data/nisircop.db # Relative path for Docker volume
    driver-class-name: org.sqlite.JDBC
  eureka:
    client:
      service-url:
        defaultZone: http://discovery-server:8761/eureka/ # Docker-specific Eureka URL