#!/bin/bash
# Start all services in the correct order
# This script starts services in separate terminal tabs/windows
# For production, use systemd or a process manager like PM2

echo "==================================="
echo "NISIRCOP-LE Service Startup Script"
echo "==================================="
echo ""
echo "This script will guide you through starting all services."
echo "You'll need to run each service in a separate terminal window."
echo ""
echo "Services must be started in this order:"
echo "1. Discovery Server (port 8761) - MUST START FIRST"
echo "2. API Gateway (port 8080)"
echo "3. Auth Service (port 8081)"
echo "4. User Service (port 8085)"
echo "5. Geographic Service (port 8084)"
echo "6. Incident Service (port 8083)"
echo "7. Analytics Service (port 8086)"
echo "8. Frontend (port 3000)"
echo ""
echo "Startup Instructions:"
echo "====================="
echo ""
echo "Terminal 1 - Discovery Server:"
echo "  ./scripts/run-discovery-server.sh"
echo "  Wait for 'Eureka Server started' message (~30 seconds)"
echo ""
echo "Terminal 2 - API Gateway:"
echo "  ./scripts/run-api-gateway.sh"
echo ""
echo "Terminal 3 - Auth Service:"
echo "  ./scripts/run-auth-service.sh"
echo ""
echo "Terminal 4 - User Service:"
echo "  ./scripts/run-user-service.sh"
echo ""
echo "Terminal 5 - Geographic Service:"
echo "  ./scripts/run-geographic-service.sh"
echo ""
echo "Terminal 6 - Incident Service:"
echo "  ./scripts/run-incident-service.sh"
echo ""
echo "Terminal 7 - Analytics Service:"
echo "  ./scripts/run-analytics-service.sh"
echo ""
echo "Terminal 8 - Frontend:"
echo "  ./scripts/run-frontend.sh"
echo ""
echo "Once all services are running:"
echo "- Eureka Dashboard: http://localhost:8761"
echo "- API Gateway: http://localhost:8080"
echo "- Frontend: http://localhost:3000"
echo ""
echo "==================================="